# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-30 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170905_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='commstatus',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
