# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-01 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20181101_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commstatus', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
    ]
