# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-07 01:57
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_auto_20181107_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commtype', models.CharField(blank=True, max_length=1000)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('slots', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
