# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-14 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20181112_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='artstyle',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='commstatus',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='willdraw',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wontdraw',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
