# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-16 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20181115_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
