# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-16 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.CharField(default='img/no-image.jpg', max_length=1000),
        ),
    ]
