# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-19 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20181116_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='commissions',
            field=models.ManyToManyField(related_name='profile', to='api.Commission'),
        ),
    ]
