# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-23 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20181119_0520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='user',
        ),
        migrations.AddField(
            model_name='commission',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='api.Profile'),
            preserve_default=False,
        ),
    ]
