# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-11 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20181123_2039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiKey',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
